### PR TITLE
fixed responsiveness for highlighted events

### LINKED ISSUE #122: responsiveness of highlighted events section
image

### PR DESCRIPTION
**Pull request by kayliezhao**
iphone 12 pro responsiveness image
image

### CODE REVIEW

**Review by stanleylew5 — CHANGES_REQUESTED** [review]
image

you don't need to finish this by tomorrow so don't stress

let's make the squares for the carousel items larger so the image doesn't look squashed on mobile. you can also move the items more to the left/right so increase the width or whatever of the component for mobile.

for fix all the empty space above for mobile. 

also bring the highlighted in highlighted events text higher above

**Comment by kayliezhao** [comment]
fixed the empty space, highlighted events gap, and sizing of the images to fit better for mobile responsiveness
image

**Review by stanleylew5 — CHANGES_REQUESTED** [review]
there is an overlap between the cards which we don't want cause it covers the text of the left/right cards, try and remove the overlap so it looks like how it looks on desktop 
image
you can move the cards even more to the left/right

image

spacing for the text below looks fine on mobile screens now but i think you changed a value that affected it for desktops/monitors cause its too large now so fix that
image

**Comment by kayliezhao** [comment]
fixed iphone spacing of slides
image
fixed desktop highlights spacing
image

**Pull request merged**
